site_name: 'Yncrea - Intro to Cloud Computing Course'
nav:
  - Home: 'README.md'
  - Prerequisites: prerequisites.md
  - SpringBoot Lab: javaspringboot.md
  - Getting Started with Maven: maven.md
  - Docker Lab: docker.md
  - Kubernetes Lab: kubernetes.md
  - Getting Started with Github: github.md
  - Github Actions Lab: github-actions.md
  - Getting Started with AWS: aws.md
  - CloudFormation Deployment: cloudformation.md
  - Deploy Containers with ECS: ecs.md
  - Cloudformation Linting: cfn-nag.md
  - EKS Setup: eks.md
theme:
  name: 'material'
  logo: files/yncrea.png
  favicon: files/yncrea.png
  palette:
    primary: blue
    accent: blue
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
copyright: '&copy; 2020 Julien Berger'