site_name: 'Yncrea - Intro to Cloud Computing Course'

# Repository
repo_name: yncrea-cloudcomputing
repo_url: https://github.com/jurocknsail/yncrea-cloudcomputing
edit_uri: ""
site_description: >-
  This training material is part of <b>ITII 3 - Cloud Computing Course</b> for <b>YNCREA Toulon.</b>
  <br><br>
  <i>The course takes place over two days and intends to give students
  an overview of all technologies that are evolving around Continuous Integration and Delivery
  with a special focus on Cloud Technologies.</i>

nav:
  - Home: index.md
  - Day#1:
    - Env - Prerequisites: prerequisites.md
    - Code - SpringBoot Lab: javaspringboot.md
    - Code - Get Started with Maven: maven.md
    - Docker - Containers Lab: docker.md
    - Kubernetes - Charts Lab: kubernetes.md
    - Github - Git Repository Lab: github.md
    - Github - Actions Lab / CI: github-actions.md
  - Day#2:
    - AWS - Basics Lab: aws.md
    - AWS - CloudFormation with Github Actions / CD: cloudformation.md
    - AWS - ECS Lab: ecs.md
    - AWS - CloudFormation Linting: cfn-nag.md
    - AWS - EKS Lab: eks.md
    - AWS - Cleanup: cleanup.md
  - Going Further:
    - Ideas: further.md

theme:
  language: en
  name: 'material'
  logo: files/yncrea.png
  favicon: files/yncrea.png
  palette:
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - tabs
    - instant
  custom_dir: material

markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
copyright: '&copy; 2020 Julien Berger'

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jurocknsail
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/repository/docker/jurocknsail/yncrea-hellomicro
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/julien-berger-0a9671154/

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto