apiVersion: apps/v1
kind: Deployment
metadata:
  name: yncrea-hellomicro
  labels:
    app.kubernetes.io/name: yncrea-hellomicro

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: yncrea-hellomicro
  template:
    metadata:
      labels:
        app.kubernetes.io/name: yncrea-hellomicro
    spec:
      containers:
        - name: yncrea-hellomicro
          image: test/cloudcomputing:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP