apiVersion: v1
kind: Service
metadata:
  name: yncrea-hellomicro-service
spec:
  selector:
    app.kubernetes.io/name: yncrea-hellomicro
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort