apiVersion: v1
kind: Service
metadata:
  name: {{ include "yncrea-hellomicro.fullname" . }}
  labels:
    {{- include "yncrea-hellomicro.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 31001
  selector:
    {{- include "yncrea-hellomicro.selectorLabels" . | nindent 4 }}
