name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  my-job:
    name: CI/CD Job
    runs-on: ubuntu-latest
    steps:

      - name: Checkout master branch
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Maven Clean, Test & Package
        run: mvn -B clean package --file pom.xml

      - name: Docker Build & Push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: jurocknsail/yncrea-hellomicro
          tag_with_ref: true
          tag_with_sha: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy IaC
        run: aws cloudformation deploy --template-file src/infra/autoscaling_tropo.yaml --stack-name infra-stack

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}